"use client";import{useEffect,useRef,useState}from"react";import{Camera,Fingerprint,ImagePlus,Loader2,LockKeyhole,LogOut,Plus,ScanFace,ShieldCheck,UserRound}from"lucide-react";
type Person={id:string;name:string;notes:string;sampleCount:number};type Sample={personId:string;name:string;embedding:number[]};
export default function Home(){const[auth,setAuth]=useState<boolean|null>(null),[password,setPassword]=useState(""),[people,setPeople]=useState<Person[]>([]),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[tab,setTab]=useState("identify"),[selected,setSelected]=useState(""),[result,setResult]=useState<{name:string;confidence:number}|null>(null),[streaming,setStreaming]=useState(false);const video=useRef<HTMLVideoElement>(null);
useEffect(()=>{fetch("/api/auth/session").then(r=>r.json()).then(x=>setAuth(x.authenticated)).catch(()=>setAuth(false))},[]);useEffect(()=>{if(auth){loadPeople();loadModels()}},[auth]);
async function loadPeople(){const r=await fetch("/api/people");if(r.ok)setPeople((await r.json()).people)}
async function loadModels(){try{const f=await import("@vladmandic/face-api");await Promise.all([f.nets.tinyFaceDetector.loadFromUri("/models"),f.nets.faceLandmark68Net.loadFromUri("/models"),f.nets.faceRecognitionNet.loadFromUri("/models")]);setReady(true)}catch{alert("מנוע הזיהוי לא נטען")}}
async function descriptor(file:File){const f=await import("@vladmandic/face-api"),img=await f.bufferToImage(file),x=await f.detectSingleFace(img,new f.TinyFaceDetectorOptions({inputSize:416,scoreThreshold:.45})).withFaceLandmarks().withFaceDescriptor();if(!x)throw Error("לא נמצאו פנים ברורות");return Array.from(x.descriptor)}
async function identify(file:File){setBusy(true);setResult(null);try{const q=await descriptor(file),r=await fetch("/api/embeddings"),s:Sample[]=(await r.json()).samples;if(!s.length)throw Error("המאגר עדיין ריק");const d=(a:number[],b:number[])=>Math.sqrt(a.reduce((n,v,i)=>n+(v-b[i])**2,0)),rank=s.map(x=>({...x,d:d(q,x.embedding)})).sort((a,b)=>a.d-b.d)[0];if(rank.d>.58)throw Error("לא נמצאה התאמה מספיק טובה");setResult({name:rank.name,confidence:Math.round((1-rank.d)*100)})}catch(e){alert(e instanceof Error?e.message:"הזיהוי נכשל")}finally{setBusy(false)}}
async function train(file:File){if(!selected)return alert("בחר אדם");setBusy(true);try{const v=await descriptor(file),form=new FormData();form.set("image",file);form.set("embedding",JSON.stringify(v));const r=await fetch(`/api/people/${selected}/samples`,{method:"POST",body:form});if(!r.ok)throw Error((await r.json()).error);await loadPeople();alert("התמונה נוספה לאימון")}catch(e){alert(e instanceof Error?e.message:"האימון נכשל")}finally{setBusy(false)}}
async function startCamera(){try{const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:"environment"}});setStreaming(true);setTimeout(()=>{if(video.current)video.current.srcObject=s})}catch{alert("לא ניתנה גישה למצלמה")}}
function capture(){if(!video.current)return;const c=document.createElement("canvas");c.width=video.current.videoWidth;c.height=video.current.videoHeight;c.getContext("2d")?.drawImage(video.current,0,0);c.toBlob(b=>b&&identify(new File([b],"camera.jpg",{type:"image/jpeg"})),"image/jpeg",.9)}
if(auth===null)return <main className="center dark"><Loader2 className="spin"/></main>;if(!auth)return <main className="center dark"><form className="login" onSubmit={async e=>{e.preventDefault();setBusy(true);const r=await fetch("/api/auth/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password})});setBusy(false);if(r.ok)setAuth(true);else alert("סיסמה שגויה")}}><div className="logo"><Fingerprint/></div><small>FACE VAULT</small><h1>כניסה למערכת</h1><p>המאגר הפרטי שלך מוגן בסיסמה</p><label>סיסמה</label><div className="pass"><LockKeyhole/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoFocus/></div><button disabled={busy}>{busy?"מתחבר...":"כניסה מאובטחת"}</button><span><ShieldCheck/>המידע נשמר באופן פרטי</span></form></main>;
return <main className="app"><aside><div className="brand"><div className="logo mini"><Fingerprint/></div><b>Face Vault</b></div><div className="stat"><UserRound/><strong>{people.length}</strong><span>פרופילים</span></div><div className="stat"><ScanFace/><strong>{people.reduce((n,p)=>n+Number(p.sampleCount),0)}</strong><span>דוגמאות אימון</span></div><p className="safe"><ShieldCheck/>חתימות הפנים נוצרות במכשיר שלך.</p><button className="logout" onClick={async()=>{await fetch("/api/auth/logout",{method:"POST"});location.reload()}}><LogOut/>יציאה</button></aside><section><header><div><small>מערכת ניהול וזיהוי</small><h1>מה נזהה היום?</h1></div><em className={ready?"ok":""}>{ready?"● מנוע הזיהוי מוכן":"● טוען מנוע..."}</em></header><nav>{[["identify","זיהוי"],["train","אימון"],["people","אנשים"]].map(x=><button key={x[0]} className={tab===x[0]?"active":""} onClick={()=>setTab(x[0])}>{x[1]}</button>)}</nav>
{tab==="identify"&&<div className="panel grid"><div><small>זיהוי מהיר</small><h2>העלה תמונה או צלם עכשיו</h2><p>השתמש בתמונה חדה, עם פנים גלויות ובתאורה טובה.</p><div className="buttons"><label className="primary"><ImagePlus/>בחירת תמונה<input hidden type="file" accept="image/*" disabled={!ready||busy} onChange={e=>e.target.files?.[0]&&identify(e.target.files[0])}/></label><button onClick={startCamera}><Camera/>מצלמה</button></div>{streaming&&<div className="camera"><video ref={video} autoPlay playsInline/><button onClick={capture}>זהה עכשיו</button></div>}</div><div className={"result "+(result?"match":"")}>{busy?<><Loader2 className="spin"/><h3>סורק...</h3></>:result?<><ShieldCheck/><small>נמצאה התאמה</small><h3>{result.name}</h3><b>{result.confidence}% ביטחון</b></>:<><ScanFace/><h3>כאן תופיע התוצאה</h3></>}</div></div>}
{tab==="train"&&<div className="panel"><small>שיפור הדיוק</small><h2>הוסף תמונת אימון</h2><p>מומלץ להוסיף 3–5 תמונות מזוויות שונות לכל אדם.</p><div className="buttons"><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">בחר אדם</option>{people.map(p=><option key={p.id} value={p.id}>{p.name} · {p.sampleCount}</option>)}</select><label className="primary"><ImagePlus/>הוסף תמונה<input hidden type="file" accept="image/*" disabled={!ready||busy} onChange={e=>e.target.files?.[0]&&train(e.target.files[0])}/></label></div></div>}
{tab==="people"&&<div className="panel"><div className="head"><div><small>המאגר</small><h2>פרופילים</h2></div><button className="primary" onClick={async()=>{const name=prompt("שם מלא");if(!name)return;const notes=prompt("הערות (אופציונלי)")||"";const r=await fetch("/api/people",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,notes})});if(r.ok)await loadPeople()}}><Plus/>אדם חדש</button></div><div className="people">{people.map(p=><article key={p.id}><div className="avatar"><UserRound/></div><div><h3>{p.name}</h3><p>{p.notes||"ללא הערות"}</p><small>{p.sampleCount} תמונות אימון</small></div></article>)}</div></div>}</section></main>}
